name: BandwagonHost Scraper

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Scraper
      run: |
        python scripts/scraper.py

    - name: Check for changes
      id: check_changes
      run: |
        if [[ -z $(git status -s data/vps_data.json) ]]; then
          echo "No changes detected."
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected."
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and Push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/vps_data.json
        git commit -m "Update VPS data from scraper [skip ci]"
        git push
